### ISSUE TITLE
CurveRefs definition incomplete in 18?

### ISSUE THREAD

**Issue by cthompso** [qLab/qLib#1048]
Hello-

I am new to qLib, so this may be a PEBKAC issue, but I'm noticing that when loading some of the example hip files in Houdini 18, certain nodes aren't working correctly. Most notably CurveRefs. I see these warnings when checking them:

Warning 
This node is using an incomplete asset definition. It will not
function properly until the asset library containing the full
definition is installed. 

Other qL nodes appear to work as expected though. Does anyone know what this might be?

thanks,

Colin

**Comment by cthompso** [comment]
I should also note that when I open a blank houdini session and drop down a Curve Refs node in a SOP context, the parameters for that node appear different than when I load up one of the example files that uses Curve Refs nodes, such as advect_bg_pointcloud_ql_POP.hip. Perhaps the example files are just using out of date representations?

**Comment by johnnyquest** [comment]
Hey @cthompso , yep that particular hip file is outdated (in fact, lots of them are, and would need maintenance). The Curve Refs qL SOP was replaced by Curve Frame qL SOP (which will probably be retired in a year or so, since in H18 there's a built-in node Orientations from Curve SOP that does the same thing but has more options).

**Comment by johnnyquest** [comment]
This particular example file is from 2013, and amongst other things it also has an old popnet in it which is not supported any more... I'll remove this and put in a ticket to create an example for the Curve Frame qL SOP.

**Comment by johnnyquest** [comment]
https://github.com/qLab/qLib/issues/1049
