### ISSUE TITLE
Volume Shape qL SOP should support name attribute?

### ISSUE THREAD

**Issue by johnnyquest** [qLab/qLib#1051]
- core/boundary geos could be paired up by name attribute
- output name attribute (cos "name" would be "density" usually)
- options to merge them? -> yes
- let's do a connectivity-based thing instead, automatically

**Comment by cofhaker9712** [comment]
Muito bom

**Comment by johnnyquest** [comment]
@cofhaker9712 thanks for the feedback (I google-translated it :D) Is this something that you'd find useful?

**Comment by johnnyquest** [comment]
@cofhaker9712 better later than never! rolling release v0.2.246 has this now :) cheers
