### ISSUE TITLE
Support for Python 3

### ISSUE THREAD

**Issue by melMass** [qLab/qLib#1151]
Now that Python 3 is mature enough in Houdini, 
is there a plan to switch to it either in master or in a separate branch?

For now, the only issues I've found are all the print statements missing parentheses, and `xrange` being simply `range` now.

**Comment by melMass** [comment]
I just found out that the python3 version of Houdini ships with a modified Py23convert binary that accepts both python scripts and HDAs!

**Comment by johnnyquest** [comment]
@melMass ha, that's nice, thanks for the tip, I'll check it out. Would be nice if the python3 code would remain py2.x compatible as well, but we'll see (I haven't had much time to look into this). Good ticket though, thanks

**Comment by johnnyquest** [comment]
also, note to self: come up w/ something that works both in py2 and py3 if possible (without if-like directives all over the place)

**Comment by johnnyquest** [comment]
test
- build attrib menu
- ramp interpolation change menu items (RMB menu)

**Comment by johnnyquest** [comment]
test
- build attrib menu
- ramp interpolation change menu items (RMB menu)

extracted hdas
grep -iR "print " * | grep -v Contents (to find most of the python-like stuff)
- DialogScript (python as multi-line string :()
- PythonModule
- PythonCook
- Tools.shelf?
- PreFirstCreate
- OnLoaded
- OnCreated

**Comment by johnnyquest** [comment]
Things to check whether they work properly under python 3:
- attribute lister popups
- ramp attrib interpolation changer (parm RMB menu)
- shelf buttons
- Muto qL ROP
- Environment qL OBJ

**Comment by larrybrit** [comment]
I've been using qlib with the regular builds of houdini just fine. But upgrading to python 3 with both the latest of H and qLib and I get errors everywhere. Here's the first one from the terminal upon lauching houdini : 
Not sure what I am doing wrong...



= = = Resources registration = = =
/home/xxx/houdini18.5/qLib/viewer_states/qLib_camera_zoom_vertigo_ql_dop.py
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/hfs18.5.696_py3/houdini/python3.7libs/viewerstate/utils.py", line 942, in register_pystate
    mod = importlib.import_module(module_name)
  File "/opt/hfs18.5.696_py3/python/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/xxx/houdini18.5/qLib/viewer_states/qLib_camera_zoom_vertigo_ql_dop.py", line 4, in <module>
    import qLibCameraZoomVertigo
  File "/home/xxx/houdini18.5/qLib/viewer_states/qLibCameraZoomVertigo.py", line 55
    print "prim:", prim
                ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("prim:", prim)?

**Comment by larrybrit** [comment]
I'm on ubuntu 20.04 if that makes any difference...

**Comment by larrybrit** [comment]
Ok, never mind, I trashed my old qLib folder full with the latest and older version, installed the latest from scratch and it worked.
thank for looking into it anyways.

**Comment by johnnyquest** [comment]
@larrybrit @melMass I imagine there might be another round of python 3 amazingness, so please report any issues you might run into

**Comment by larrybrit** [comment]
Will do. Thanks!
