### ISSUE TITLE
wrong placement of qLib network editor menu item in H18.5?

### ISSUE THREAD

**Issue by johnnyquest** [qLab/qLib#1180]
also getting this (18.5.402)
```
 '/opt/hfs18.5/packages/kinefx/MainMenuCommon.xml':
Could not find the parent element 'import_files' for 'h.import_mocap'.
Cannot set order: element 'h.import_mocap' has no parent.
Cannot set order: element 'h.import_mocap' has no parent.
Could not find the parent element 'windows_menu' for 'h.open_rigtree'.
Cannot set order: element 'h.open_rigtree' has no parent.
Cannot set order: element 'h.open_rigtree' has no parent.
Error while parsing a menu definition file
 '/home/tusi/houdini18.0/qLib-dev/NetworkViewMenu.xml':
Cannot find element help_menu' needed for ordering of 'qLib_network_view_menu'.
```

**Comment by robmoggach** [comment]
I'm getting a conflict with SideFXLabs -
```
Error while parsing a menu definition file
 '$HSITE/houdini18.5/packages/qlib/NetworkViewMenu.xml':
Cannot find element 'help_menu' needed for ordering of 'qLib_network_view_menu'.
```

Disabling sidefxlabs stops the error.

**Comment by robmoggach** [comment]
ohh... and i had that kinefx error too... so i just deleted kinefx lol

**Comment by johnnyquest** [comment]
@robmoggach this fixed in a later daily build

**Comment by johnnyquest** [comment]
@robmoggach see #1185 (I just closed it, forgot to close it), I'm closing this one too, cos it seems like the same thing. Feel free to open a new ticket on this if you're still getting issues with a recent daily build. Also, thanks for the comment! cheers

**Comment by revilo3d** [comment]
I'm still getting this issue when I load qLib,  but it's clashing with Renderman in my instance. If I remove the renderman package everything works as expected.

Houdini 19.0.383 py 3.
