### ISSUE TITLE
menu only loads in FX

### ISSUE THREAD

**Issue by simonreeves** [qLab/qLib#1266]
Hello!
I had for a while felt like the qLib menu is there sometimes and sometimes not - finally I have worked out that it is because you use `MainMenuMaster.xml` and not `MainMenuCommon.xml` as described in [the houdini docs](https://www.sidefx.com/docs/houdini/basics/config_menus.html#configuration-files)

Perhaps it could change if it is not intended? I think it should be safe..

Thanks for all your work on the excellent qLib! 🙏

**Comment by johnnyquest** [comment]
Ha! Thanks for pointing this out. Yep, should be safe, not a difficult fix

**Comment by johnnyquest** [comment]
@simonreeves see v0.2.196 -- I'm closing this ticket, but let me know if it doesn't work for some reason
