### ISSUE TITLE
qlib in latets houdini build 18.5.672 - python 3 - errors in shell

### ISSUE THREAD

**Issue by Rognva1dr** [qLab/qLib#1286]
Hi 

I just installed latest production build 18.5.672 py3 - and when reading the qlib package .json file _ i get the following errors in my shell:

Exception in thread Thread-2:
Traceback (most recent call last):
  File "/opt/hfs18.5.672/python/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/opt/hfs18.5.672/houdini/python3.7libs/houdinihelp/api.py", line 589, in run
    indexer.update_with(w, pages, overlay=True)
  File "/opt/hfs18.5.672/houdini/python3.7libs/bookish/search.py", line 486, in update_with
    writer, pages, update_paths, needs_delete=changed
  File "/opt/hfs18.5.672/houdini/python3.7libs/bookish/search.py", line 516, in index_paths_with
    for doc in self.documents(pages, path):
  File "/opt/hfs18.5.672/houdini/python3.7libs/bookish/search.py", line 417, in documents
    jsondata = pages.json(path, postprocess=False)
  File "/opt/hfs18.5.672/houdini/python3.7libs/bookish/wiki/wikipages.py", line 607, in json
    self._pre_pipeline.apply(jsondata, wcontext)
  File "/opt/hfs18.5.672/houdini/python3.7libs/bookish/wiki/pipeline.py", line 118, in apply
    v.apply(block, context)
  File "/opt/hfs18.5.672/houdini/python3.7libs/houdinihelp/hpages.py", line 324, in apply
    self.apply(subblock, context)
  File "/opt/hfs18.5.672/houdini/python3.7libs/houdinihelp/hpages.py", line 320, in apply
    self.text(block["text"], context)
  File "/opt/hfs18.5.672/houdini/python3.7libs/houdinihelp/hpages.py", line 340, in text
    value = self._parse_opdef(context["path"], value)
  File "/opt/hfs18.5.672/houdini/python3.7libs/houdinihelp/hpages.py", line 284, in _parse_opdef
    table, nodetype = nodetype.split("/")
ValueError: not enough values to unpack (expected 2, got 1)

Not sure if this is qLib or Houdini - would you know?

Thank you for the help

**Comment by Rognva1dr** [comment]
my qLib_package_linux.json  reads as follows

{
    "recommends": "houdini_version >= '17.5.321'",

    "env": [
        {
            "QLIB": "/mnt/FRAMESTORE/common/dev/pipeline/houdini/qLib",
        },
        {
            "QOTL": "$QLIB/otls",
        },
        {
            "HOUDINI_OTLSCAN_PATH": "$QOTL/base:$QOTL/future:$QOTL/experimental:$HOUDINI_OTLSCAN_PATH",
        },
    ],
    
    "path": "$QLIB",
}

**Comment by ReimuSG** [comment]
I checked the HDA file in qLib, and then found that **camera_plane_ql** caused this error because of the reason for the node's help documentation included a illegal character, after I removed it, this error was solved.

**The content of the problematic line is:**
[Image:opdef:Sop/qLib::camera_plane_ql::1?camera_plane_ql_sop_main.png]

**change into:**
[Image:opdef:Sop/qLib::camera_plane_ql::1camera_plane_ql_sop_main.png]

Of course, even if this problem is not repaired, it will not affect the use of this node, it will only lead to this node. :D

**Comment by Rognva1dr** [comment]
Thanks @ReimuSG  - good to know its not major

Just seen a new production build 18.5.696 - going to see if the message appears in this new build.......

**Comment by Rognva1dr** [comment]
Yep - same output error in latest production build 18.5.696...

**Comment by johnnyquest** [comment]
@ReimuSG which one is the illegal character on that line?

**Comment by ReimuSG** [comment]
@johnnyquest 
This problem appears on the 13th line of the  **camera_plane_ql** _HDA Help page_, its content is like this:

`
[Image:opdef:Sop/qLib::camera_plane_ql::1?camera_plane_ql_sop_main.png]
`

I tried to remove the exception character, but I didn't seem to solve the problem... so I deleted this line.

**Comment by johnnyquest** [comment]
@ReimuSG aaah, apparently it should be like this --

`[Image:opdef:/qLib::Sop/camera_plane_ql::2?camera_plane_ql_sop_main.png]`

**Comment by johnnyquest** [comment]
But it's just the camera plane object nodes right? I don't see anything in the frustum obj node. On it

**Comment by ReimuSG** [comment]
> But it's just the camera plane object nodes right? I don't see anything in the frustum obj node. On it

Yep~this problem is only on **camera_plane_ql & camera_plane_ql_2**

As for the frustum obj node, I don't seem to find errors...

**Comment by johnnyquest** [comment]
oops, github closed it -- I just put up a new rolling release, @ReimuSG @Rognva1dr please test it and if it works I'll close the ticket again :)

**Comment by ReimuSG** [comment]
Nice going! this problem has been solved, thanks for your timely maintenance :D @johnnyquest

**Comment by johnnyquest** [comment]
cool cool, no worries, happy to help. closing this one then

**Comment by Rognva1dr** [comment]
Thank you @johnnyquest and @ReimuSG - I can concur that worked perfectly.

No more errors - cheers!
