### ISSUE TITLE
Assets Not Loading Houdini 19.0.622 Mac OS

### ISSUE THREAD

**Issue by keithrondinelli** [qLab/qLib#1322]
Using either the package method or the Houdini.env method, the Qlib OTLs are not showing up, only the Qlib menu in Houdini, and a "Qlib Shelf" in my tools list, with a Sticky Note tool. I've got several packages installed using the package method, so I'm familiar with how it works, and I've followed all instructions.

**Comment by johnnyquest** [comment]
Hi @keithrondinelli sorry I don't have access to MacOS so I can't even test this. It's weird, because usually when there's a problem it's quite the opposite (i.e. otls show up but UI elements act up). Maybe try with a different (later) Houdini build? Please let me know if the issue is still there.

**Comment by johnnyquest** [comment]
hey @keithrondinelli I was wondering if you still have this issue?

**Comment by johnnyquest** [comment]
hi @keithrondinelli I'm closing this ticket. If you still have this issue, please reopen and mention me. Thank you
