### ISSUE TITLE
json syntax

### ISSUE THREAD

**Issue by crmabs** [qLab/qLib#1457]
in this file  qLib_package_linux.json  the json is not 100% correct. No comma is needed at the end of lines 6, 9, 12, 13, 16.
installs and works flawlessly and probably won't make any difference.. i was just surprised that the json linter is complaining.  
o/

**Comment by johnnyquest** [comment]
aaaaaaaand done. likely a unified json is coming, see #1440

**Comment by crmabs** [comment]
and now i noticed that "trailing commas" is a thing - parser specific optional setting but it's a thing.
