### ISSUE TITLE
video tutorial: qLib installation 

### ISSUE THREAD

**Issue by johnnyquest** [qLab/qLib#313]
a comprehensive video walk-through on how to properly install qLib:
- facebook, release and dev branches ; how to download the dev branch
- install archive contents into a fresh houdini config folder
- explain otls, galleries, scripts 
- show how to check for all of them if installed

**Comment by jordibares** [comment]
It would be great to cover the Linux, Windows and OS X flavours, they are slightly different and quite painful sometimes.

**Comment by johnnyquest** [comment]
Yeah... I think the main difference between Linux/OSX and Windows is the path separator (which is colon `:` on linux/osx and semicolon `;` on windows -- as if the slash/backslash things wasn't enough).
