### ISSUE TITLE
move from "experimental"

### ISSUE THREAD

**Issue by johnnyquest** [qLab/qLib#331]
If all in favor, I'd like to move these to at least "future". (We're neglecting this for a long time and everything became experimental now... :cold_sweat: )

I suggest all deformers going straight to base/ :tada: 

- ~~Alembic Xform OBJ/SOP~~
- ~~Bias Deformer~~
- ~~Clip by Bounds~~
- ~~Curve Frame~~
- Desaturate
- ~~Fluid Source qL~~
- ~~Gas Resize Fluid Dynamic qL~~
- ~~Group qL~~
- ~~Mountain Deformer~~
- ~~Poly Wrap~~
- ~~Quick Poly Caps (?)~~
- ~~Ray qL~~
- ~~Rivet qL SOP~~
- ~~Scatter qL~~
- ~~Shot Builder qL OBJ~~
- ~~Switch Off qL SOP, DOP~~
- ~~Taper qL SOP~~
- ~~UV Point Cloud SOP/COP2~~
- Xform to Plane SOP/VOP

**Comment by dbukovec** [comment]
ok by me

**Comment by johnnyquest** [comment]
commit a99ffed494807a55f4
