### ISSUE TITLE
attrib shape ql SOP errors

### ISSUE THREAD

**Issue by NNois** [qLab/qLib#334]
i'm having this error on scene reloads... even on a blank one with only the attrib shape SOP.
Any idea ???

![2015-03-19_18h10_32](https://cloud.githubusercontent.com/assets/2362053/6736158/5cffe5b4-ce63-11e4-9fbf-0ac476635ec4.png)

**Comment by johnnyquest** [comment]
Yes, this basically means the Attrib Shape qL SOP wasn't resaved in H14 (I'm assuming you're getting this under H14).

**Comment by johnnyquest** [comment]
Should be okay now -- pull/download the latest dev branch version.

**Comment by gadfly16** [comment]
This is just a warning. While it's ugly and irritating it causes no harm.
We will fix it, but until then please use it as it is.
