### ISSUE TITLE
H15: parameters are not created when node created

### ISSUE THREAD

**Issue by groundflyer** [qLab/qLib#398]
Nodes are created as if with run_init_scripts = false, a lot of parameters are not installed.

**Comment by johnnyquest** [comment]
hi -- could you be a bit more specific on this one? is this a qLib-related issue? (maybe provide a test case as well?)

**Comment by groundflyer** [comment]
Ooops.
I've lost "s" in this string while copying config.
HOUDINI_SCRIPT_PATH = $QLIB/scripts:@/script
