### ISSUE TITLE
ToggleViewportBackgroundColor_qL shelf tool implies that bg color is not DARK

### ISSUE THREAD

**Issue by bonsak** [qLab/qLib#406]
If your default background color is DARK, you will have to use the shelf tool twice to get a GREY background when the tool is used for the first time.

- Set your Background color scheme to "Dark"
- Save As Default
- Make new document
- Use "ToggleViewportBackgroundColor_qL"
> Background is set to DARK (Same as your default color)

Couldn't figure out how to "get current background color" with python or i would have fixed this myself.

**Comment by johnnyquest** [comment]
> Couldn't figure out how to "get current background color" with python or i would have fixed this myself.

Exactly! :) I couldn't find a way to _query_ the current background color, so if you have a dark background, you'll have to click the button twice for the first time.

**Comment by bonsak** [comment]
:)
