### ISSUE TITLE
Updated qLibProFlat.hcs

### ISSUE THREAD

**Issue by NNois** [qLab/qLib#437]
Hi, the qLibProFlat.hcs isn't really up to date compared to your fb screenshoots ;-) there's some border color missing and other things.
Could you release an updated version ?

**Comment by johnnyquest** [comment]
it's supposed to be the latest version (what we have on github is always the latest version of everything on my machine). make sure you have "Color Pane Headers with Network Contexts" in your prefs. (If you still have problems i'm glad to look into it if you can be more specific than "other things" :) e.g. screenshots or something)

**Comment by johnnyquest** [comment]
see also #419

**Comment by johnnyquest** [comment]
@NNois i checked it out and it looks the same to me (compared regular dark and qLib-dark-flat ones in the default "Build" desktop), see my previous comment on the prefs thing.

if you still have issues, please get back to me, until then i'm closing this. cheers!!
