### ISSUE TITLE
Distribute qL SOP issue

### ISSUE THREAD

**Issue by johnnyquest** [qLab/qLib#451]
check this --

https://groups.google.com/forum/#!topic/qlib/8mbEYa_FF3w

- doesn't work in H15, either
- also, make sure the loop "variable" in the ForEach is unique

**Comment by johnnyquest** [comment]
to fix: go to foreach_iteration/vopsop_distribute/snippet1 and type P in Bindings to Export

**Comment by flipswitchingmonkey** [comment]
Also check whether you need to remove the @ from the P variable.  Writing back to @P does not seem to work or at least gives a different result from writing to P after it was added to the Bindings to Export.

**Comment by johnnyquest** [comment]
ahhhhh okay, thanks for checking it out. although using P (then connecting the snippet's outP to the global output P) should also work the exact same way.

**Comment by johnnyquest** [comment]
Ok, I'm fixing it by connecting snippet1's outP to the output globals P. Seems to work. Also addressed the unique-ifying of the loop variable in the inner foreach loop.
