### ISSUE TITLE
Attrib Shape qL SOP shape scaling issue

### ISSUE THREAD

**Issue by bonsak** [qLab/qLib#476]
Add an Attrib Shape qL SOP
Set Transform -> Uniform Scale to anything but 1 and 0
Shape is scaled
Set Transform -> Uniform Scale to 0
Shape scale is 1 (unmodified). Should be 0

**Comment by johnnyquest** [comment]
yeah, i see that not working -- it's a maketransform() call within the internal Xform Builder qL (vop) asset, my guess is that the maketransform() doesn't appreciate a scale value of 0.

You can get similarly weird results if you set any of the x/y/z scales to zero. If you set _all_ of them to 0, you'll still get an unit-sized shape (scale 1).

**Comment by bonsak** [comment]
Yes it seems maketransform() doesn't like scale = 0. It would still be nice to be able to scale things down to zero though.

**Comment by bonsak** [comment]
Not going to be changed by sesi anytime soon it seems. Got word that this behavior is unintended but that it is buried deep in some low level lib that changing it might have serious impact on a number of other things :)

**Comment by bonsak** [comment]
Just got word that this will be fixed in the next major release :)

**Comment by johnnyquest** [comment]
@bonsak ah really? that's a nice surprise. one or two versions ago i ran into something similar (ended up being a zero scale thing), and one of the devs told me they dare not touch the transformation code :) i'm glad they'll look into it

**Comment by bonsak** [comment]
We'll see what kind of havoc this fix will create :)

**Comment by johnnyquest** [comment]
see also #214 ...

**Comment by bonsak** [comment]
This seems to have been fixed in 16.

**Comment by johnnyquest** [comment]
@bonsak Nice! I'll check it out as soon as we get H16 :)

**Comment by johnnyquest** [comment]
Yeah this seems to be working, i'm closing this
