### ISSUE TITLE
TODO: Build an entirely VEX-based Group alternative

### ISSUE THREAD

**Issue by johnnyquest** [qLab/qLib#493]
- should be a SOP _and_ DOP version
- should look like Group qL SOP (variable number / order of of operations)
- should have a simple and easy-to-understand UI
- should include #449 and #438

**Comment by JacobSanta** [comment]
I haven't checked out the files but just putting this here for later on.
http://forums.odforce.net/topic/27830-custom-group-sop-in-vex/

**Comment by johnnyquest** [comment]
also see #516

**Comment by johnnyquest** [comment]
@JacobSanta hey i just noticed your comment, thanks man

**Comment by johnnyquest** [comment]
H16 notes:
- from the performance standpoint it's not necessary any more (e.g. compile blocks, blah blah)
- the SideFX guys don't prefer monolithic nodes (the old Group SOP just got exploded into several different group-related nodes) so that's the way we should proceed, too

The DOP thing still needs consideration, though

**Comment by johnnyquest** [comment]
i'm closing this, will open new ticket for DOPs if necessary
