### ISSUE TITLE
build a Varmap qL SOP? (auto-generation of variable mappings)

### ISSUE THREAD

**Issue by johnnyquest** [qLab/qLib#496]
hopefully varmaps will be things of the past soon, i'm just extracting the remaining relevant part of #350 here (it's mostly for oldschool nodes, qLib neither use nor encourage varmaps at all)

**Comment by JacobSanta** [comment]
Imre, there was a node I made at luma along time ago to do this. It was pretty basic but you could beef it up and qLibify it.

**Comment by johnnyquest** [comment]
@JacobSanta thanks man!! (this comes up from time to time on _very_ rare occasions, mostly when you have to do something that involves some archaic houdini functionality :))

**Comment by johnnyquest** [comment]
Varmaps are de facto obsolete, I'm closing this
