### ISSUE TITLE
v0.3.0

### ISSUE THREAD

**Issue by gadfly16** [qLab/qLib#501]
This is the official place to define and discuss what we want to do in this release.
- Restructure the project in a way that instead of folders we express implementation levels by git branches (**master**, **beta**, **experimental**).
- Clean up the project, so nothing outdated and/or otherwise useless asset remains in the library. It's important to communicate every riddance to the community even before the release so they can complain if they want.
- Switch to a daily release cycle. It needs some discussion how we going to manage this.
- Enable donations.

**Comment by johnnyquest** [comment]
I'm closing this as in the meantime we developed approaches for all of the above (except donations :D)
