### ISSUE TITLE
Volume Visualizer wrong directions

### ISSUE THREAD

**Issue by patrickFuerst** [qLab/qLib#515]
Hey, 

The Visualizer is showing the wrong directions for me. 
For example when setting teh volume velocity to a constant velocity of (0,0,1), the arrows of the visualizer are showing in the positive Y direction. 

When setting it to (1,0,0) it not showing anything at all.

**Comment by johnnyquest** [comment]
@patrickFuerst for that visualizer you have to pass _only_ the volume you want to visualize (in case of velocity, delete all other volumes except vel.*)

**Comment by patrickFuerst** [comment]
Hey , 

thanks for the tip, but unfortunately it's not working. 
Me test is just connecting a houdini volume node directly to the visualizer.

**Comment by johnnyquest** [comment]
@patrickFuerst could you somehow send a link to your hip file?

or you can try the forum, i think you can upload files there --
https://groups.google.com/forum/#!forum/qlib

**Comment by patrickFuerst** [comment]
Here we go : https://groups.google.com/forum/#!topic/qlib/zV5TiPXWWLA

**Comment by johnnyquest** [comment]
@patrickFuerst  ok got it. in the vector volume field you should type `velocity.*` (with the dot and star) instead of plain velocity (yeah i know it's awkward, the popup menu for that field should work, too, btw)

**Comment by johnnyquest** [comment]
okay, i'm closing this...

**Comment by patrickFuerst** [comment]
Hey @johnnyquest , 

thanks for the hint. Worked.
