### ISSUE TITLE
QUESTION: what's the official way of dynamically build and run code within an asset

### ISSUE THREAD

**Issue by johnnyquest** [qLab/qLib#539]
Affecting (amongst others)
- Pre Export Color Sets qL SOP
- Time Blend qL SOP

A previous method used hidden string parameters on the asset to store the generated code. This sometimes hanged Houdini and it caused problems when the assets were embedded in other assets (the asset had to be added as Editable).

I tried another method where I'm passing the generated VEX code as a string detail attribute, but it still can hang Houdini, so it's not stable. (I'd prefer this method, it's cleaner)

???

**Comment by johnnyquest** [comment]
let's try it with cachedUserData............

**Comment by JacobSanta** [comment]
Hey Imre.
I remember chatting to you about this at one point and if I remember correctly part of the reason to build the vex code in python was because of not being able to get a list of attributes on a geometry in VEX? I might be mistaken though. Just ran across this topic though trying to find the same thing.
https://www.sidefx.com/forum/topic/31699/

string pointAttrs[] = detailintrinsic(0, 'pointattribute');

**Comment by johnnyquest** [comment]
@JacobSanta ah, nice one man!! cheers

Well, the other reason is VEX is statically typed, so you can't really use a variable to refer to either a float or a vector, depending (i hope i'm making sense here). So, that's another reason why one would fall back to using python-generated vex code.

Btw, I figured out a way of how to do it (actually i looked into how the Attribute Expression SOP is implemented), and a solution that seems to work is to use a python expression in either a Snippet VOP or an Attrib Wrangle SOP. That seems to work so far (I built the new Volume Retime qL SOP around that, so it's able to process multiple fields) -- I'll update the Time Blend qL SOP at some point, too.

**Comment by johnnyquest** [comment]
THE way is to use a python expression in an Attrib Wrangle (or other wrangle-like) OP, and build the whole vex code using python. That's how the SideFX guys do it
