### ISSUE TITLE
user hotkey definitions for network editor node flag settings don't seem to work (16.0.633)

### ISSUE THREAD

**Issue by johnnyquest** [qLab/qLib#616]
e.g. the R/T/... key functionality can't seem to be remapped to the 1/2/3 keys

**Comment by JacobSanta** [comment]
Check that in your preferences for 'Network Editor, Nodes and Trees' that the option 'Flag Hotkeys Work on existing Node Selections' is toggled on.

**Comment by johnnyquest** [comment]
@JacobSanta i have it turned on. what difference should that make?

**Comment by johnnyquest** [comment]
https://github.com/qLab/HoudiniIssues/issues/15
