### ISSUE TITLE
Round Corners qL SOP wtf

### ISSUE THREAD

**Issue by johnnyquest** [qLab/qLib#64]
See example scene / Point Group example (messed-up geometry).

**Comment by johnnyquest** [comment]
@gadfly16 there's a new Bevel SOP in H15.5 that supports per-point bevel scale and whatnot, might make this one obsolete

**Comment by gadfly16** [comment]
Round Corners qL SOP works on curves instead of polygon meshes as the PolyBevel SOP does. Close this issue if I'm right.

**Comment by johnnyquest** [comment]
@gadfly16 sorry i forgot to mention that the H15,5 Bevel SOP (supposedly) works on (poly) curves, too

**Comment by gadfly16** [comment]
@johnnyquest I've tried, but I couldn't make it work. Can you send me an example file?

**Comment by johnnyquest** [comment]
@gadfly16 choose Group Type -> Points on the Poly Bevel SOP and curve point beveling will kick in.

**Comment by gadfly16** [comment]
OK. I had 15.5.480 on my home computer and that version didn't had that feature yet. I upgraded now, so I can see it now. While the two is not entirely identical, we may still get rid of Round Corners if in practice the differences are not . The difference is that Round Corners uses precise circular arcs, while PolyBevel uses some other curve:

![rc_vs_pb](https://cloud.githubusercontent.com/assets/50180/18293955/37ff8f96-7496-11e6-8c3b-7a0d1df8972d.png)

The other feature that PolyBevel misses is the *Max Segment Length" parameter, which can make arcs with smaller radius to be rendered more effectively. What do you think? Are these differences enough to keep RC afloat?

**Comment by johnnyquest** [comment]
@gadfly16 hmmmm, fair enough... we could perhaps check if PolyBevel has some other rounding options to match Round Corners.

Also, PolyBevel seems to create self-intersecting geometry where the radius is larger than the length of a poly segment, which is not ideal. I don't know how Round Corners would behave in a situation like that.

**Comment by johnnyquest** [comment]
On a related note: how about turning Rounded Rectangle into a gallery item?

**Comment by gadfly16** [comment]
It's strange that it self intersects.. but it certainly does.

I didn't find any rounding options to match mine, but poly bevel can be fed with any cross section, so I guess if someone really wants to have circular arcs she can manage with that.
