### ISSUE TITLE
Installation instructions for OSX - correction

### ISSUE THREAD

**Issue by t-marvolo** [qLab/qLib#672]
Under OSX using bash shell, qLib does not load when `export`ing the variables, as noted in the readme. Setting them normally works as expected (same as linux config):

```
QLIB=<<path to qLib install>>
QOTL=$QLIB/otls

HOUDINI_OTLSCAN_PATH=$QOTL/base:$QOTL/future:$QOTL/experimental:@/otls
HOUDINI_GALLERY_PATH=$QLIB/gallery:@/gallery
HOUDINI_TOOLBAR_PATH=$QLIB/toolbar:@/toolbar
HOUDINI_SCRIPT_PATH=$QLIB/scripts:@/scripts
```

**Comment by johnnyquest** [comment]
@t-marvolo so is bash the default shell on OSX? I'll change the README in that case...

**Comment by t-marvolo** [comment]
Yes bash is default shell in osx

**Comment by johnnyquest** [comment]
ok done
