### ISSUE TITLE
"qLib Pro Flat" color schemes both dark and light, no longer work with H17

### ISSUE THREAD

**Issue by Karlaws** [qLab/qLib#802]

**Comment by Karlaws** [comment]
Can be fixed by manually adding the files qLibDarkFlat.hcs and qLibProFlat.hcs to the config folder under Documents, for Windows. These schemes may still be missing some upgrades for H17, but seem to work regardless.

**Comment by johnnyquest** [comment]
just tested on linux (at work), the color schemes are picked up properly (there's some new H17 color entries missing, but we haven't updated the scheme itself yet)

**Comment by johnnyquest** [comment]
@Karlaws btw it should work the exact same way on windows too (especially if it worked in H16.0/16.5).
