### ISSUE TITLE
Version numbers

### ISSUE THREAD

**Issue by jordibares** [qLab/qLib#841]
Could it be possible to have a more prominent version number of the current release? may be tags in GitHub? May be in the README file?

thanks a lot

**Comment by gomdoll** [comment]
2019년 4월 5일 (금) 오후 8:55, jordibares <notifications@github.com>님이 작성:

**Comment by johnnyquest** [comment]
hi @jordibares -- we do have version numbers as tags. (Sometimes the dev branch is a few commits ahead of the latest "version" but you can still use the last version marked by the corresponding version tag)

**Comment by johnnyquest** [comment]
@jordibares does that answer your question? (i'd close the ticket if it does)

**Comment by johnnyquest** [comment]
@jordibares i'm closing this, please do comment if there's anything we need to talk about it further
