### ISSUE TITLE
No permission to access Google groups page

### ISSUE THREAD

**Issue by fatboYYYY** [qLab/qLib#858]
Hey,
as I wanted to ask a question to you, I wanted to access the forum linked in the bottom of your GH repo. https://groups.google.com/forum/#!forum/qlib
But unfortunately, I get a permission error, when trying to access it. `You do not have permission to access this content. (#418)`
It would be awesome if you guys could give people a way to access it (again?).
Thanks

**Comment by johnnyquest** [comment]
Hey @fatboYYYY -- we haven't changed anything, I think you just need to "join" the group. I set "View Topics" to "anyone on the web", so hopefully that'll give read access. (update: hm it might not -- I'm getting the same message from an incognito window, which is weird...)

Have you tried using it while signed in with a google account? We don't really want to set it to where anyone from the web can post (so it wouldn't be spammed)

**Comment by fatboYYYY** [comment]
Thanks for checking @johnnyquest 

That sounds weird. 
I logged in with my google account and now I get a similar issue:
`This group either doesn't exist, or you don't have permission to access it. If you're sure this group exists, contact the Owner of the group and ask them to give you access.`

Maybe contact google support?

**Comment by johnnyquest** [comment]
@fatboYYYY do you still have this problem?

**Comment by fatboYY** [comment]
Working now, thanks. Is that the best place to discuss?

**Comment by johnnyquest** [comment]
I get email notifications if someone writes there, so I guess the answer is "yes"... Not much conversation is going on, though. But yeah it's a legit place to discuss things, by all means.

I'll close this ticket then
