### ISSUE TITLE
Resave deformers in H17.5 (was: Error if copy/paste bend_ql)

### ISSUE THREAD

**Issue by ndeboar** [qLab/qLib#955]
When ever I copy/paste bend_ql, I get this error, which also then happens when I re-open the HIP file:
![Capture](https://user-images.githubusercontent.com/20289787/73806983-e796f100-481a-11ea-842c-37710b07e39b.JPG)

**Comment by johnnyquest** [comment]
@ndeboar yeah, probably all the deformers do that (or basically everything that has a Bound SOP inside and not resaved in H17.5). The message is harmless and doesn't affect functionality, but it's annoying. I'll update those nodes to 17.5.

- Bend, Bias, Mountain, Taper, Twist Deformer qL SOPs, Weighted Xform qL SOP
- what else?

**Comment by johnnyquest** [comment]
@ndeboar should be fine now, if you update to 0.2.123. I'm closing this ticket but please comment/reopen if you run into any issues. Cheers

**Comment by ndeboar** [comment]
Cheers!
